#%RAML 1.0 NamedExample
order: 
  customerId: 1 
  customerName: Adan Rosales 
  salesOrderNumber: 1000
  items:
    -
      itemNumber: 15215
      quantity: 3
      type: item
      price: 12
      itemDescription: it´s a doll
    -
      itemNumber: 221
      quantity: 2
      type: service
      price: 133
      itemDescription: Internet 